### PR TITLE
Remove behavior that finding by _id will find soft removed documents

### PR DESCRIPTION
**Pull request by lmachens**
Issue:  #25 .

### CODE REVIEW

**Comment by zimme** [comment]
Thanks for the PR, will try and look into this tonight.

My only concern with this is that it might be a breaking change.

Also this behaviour would stop one from being able to restore a document from client code using `_id`.

I'll have to go over the comments in #25 as I believe we talked about that there before.

:+1:

**Comment by lmachens** [comment]
I didn't test to restore a document from client side. But are you sure that it is not possible if you subscribe a removed document and call restore()?

**Comment by zimme** [comment]
I believe it's possible to do so. I guess we could go forward with this change and just add a note about the need to subscribe to removed documents to be able to restore them.

**Comment by lmachens** [comment]
For me the Readme is clear enough. Maybe you can add a note about this breaking change.
Can you update the atmosphere package cause I am using this package on production mode.

**Comment by lmachens** [comment]
There is still a problem with findOne().
Let me fix this first.

**Comment by zimme** [comment]
I'm working on it now =)

**Comment by zimme** [comment]
Try version `1.0.6-alpha.2` and see if that works as expected.

**Comment by zimme** [comment]
I tried to use your commits so you would get controbutor status on this repo but it was easier to just do it from scratch as I just removed like 1 or 2 lines of code.

**Comment by lmachens** [comment]
Did you test the case if your query is a string?

**Comment by zimme** [comment]
oh yeah, by bad, I'll add the logic for that and push a new version

**Comment by lmachens** [comment]
And if you have `return if not selector` in the first line of the hook you can get every document with .find(). 
So .find() returns everything.  find({}) returns only non-removed.

That's why I removed it and set selector to {} by default.

**Comment by zimme** [comment]
That shouldn't be true, as `find()` will actually result in `selector = {}`.

**Comment by zimme** [comment]
Try verison `1.0.6-alpha.3` and see how that works out.

**Comment by lmachens** [comment]
Sadly it will not result in selector = {}. Maybe it will in the .find() but not in the before find hook.

Give it a try:

image

```
Collection = new Mongo.Collection(null);
Collection.attachBehaviour('softRemovable');
_id = Collection.insert({a: 1});
Collection.softRemove(_id);
Collection.insert({a: 1});
Collection.insert({a: 1});
Collection.find().fetch();
Collection.find({}).fetch();
```

**Comment by lmachens** [comment]
And it looks like that the before.find hook is not executed on .update(). And if any of the update hook calls returns false, not one document is updated.
Maybe because of that:
https://github.com/matb33/meteor-collection-hooks#additional-notes

**Comment by zimme** [comment]
That's weird, I was testing this the other day and then it worked as expected but now it's only true in server code....

**Comment by lmachens** [comment]
Maybe it is a good start to require the lates version of meteor-collection-hooks.
Then it is possible to handle [upsert](https://github.com/matb33/meteor-collection-hooks/blob/master/History.md#v080) hooks too.
What is your plan?

**Comment by zimme** [comment]
What we're doing right now is just a quick fix, I'm actually working on rewriting the behaviours.

I'm pretty much done with [collectionbehaviours:timestamp](/meteor-collectionbehaviours/timestamp) and this is next on the list.

**Comment by zimme** [comment]
and yes, updating the dependency needs to be done as anyone using newer version of collection-hooks will lost this functionality on upsert.

**Comment by lmachens** [comment]
Ok, I will wait for your updates to fix the find() / find({}) and update()👍 . Tell me, if you need some help.

**Comment by zimme** [comment]
I'm trying to track it down now, I'm worried that it might be collection-hooks that is borking up the selector somewhere

**Comment by zimme** [comment]
I've tracked down the problem now and it's a problem in `matb33:collection-hooks` I'll try and fix it this weekend.

**Comment by lmachens** [comment]
Could you fix it?

**Comment by zimme** [comment]
It's pretty much fixed but as it's a breaking change for people relying on the old broken behaviour I need to get a hold of Mathieu before I merge to see how he wants to handle the update.

What you can do is to to `git checkout -b fix-unsafe-selector https://github.com/zimme/meteor-collection-hooks` into your projects packages folder and it should use collection-hooks with the fix.

**Comment by lmachens** [comment]
It looks like your PR was merged. So updating collection-hooks will fix my issues?

**Comment by zimme** [comment]
I've merged the changes yes, I can publish a test version until I've tested that package a bit more just to make sure there isn't any broken stuff.

**Comment by zimme** [comment]
@lmachens, add the new beta and see how that works. It should rely on the new rc release of collection-hooks.

Also make sure you don't have a local version of collection-hooks in your packages folder as that would take precedence.
```sh
meteor add zimme:collection-softremovable@1.0.6-beta.1
```

**Comment by lmachens** [comment]
@zimme What is the status? I didn't test the beta package yet.

**Comment by zimme** [comment]
Hey, I've been kinda busy with my "real" life so I would suggest testing the beta version and use that if it works as expected for you. I think it will be some time before I publish the new version without a beta tag.

**Comment by lmachens** [comment]
@zimme 1.0.6-beta.1 looks good, thank you! 

Still want to add me to contributors? 👍

**Comment by zimme** [comment]
I'll add a contributors section and add you there as I couldn't reafactor the commits in this PR properly.

**Pull request closed without merging**
